# Generated by Django 4.2.7 on 2024-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
