# Generated by Django 4.2.7 on 2024-04-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slider_description_alter_slider_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Введите класс иконки Font Awesome', max_length=100)),
                ('text', models.TextField(help_text='Введите текст преимущества')),
            ],
        ),
    ]
