# Generated by Django 4.2.7 on 2024-04-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
