# Generated by Django 4.2.7 on 2024-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='local_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео'),
        ),
    ]
