# Generated by Django 4.2.7 on 2024-04-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_feature_options_alter_featurevalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='feature',
        ),
    ]
