# Generated by Django 4.2.7 on 2024-04-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_products_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='feature_values',
            field=models.ManyToManyField(blank=True, related_name='products', to='goods.featurevalue', verbose_name='Характеристики'),
        ),
    ]
