# Generated by Django 4.2.7 on 2024-04-11 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products_local_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='СonditionsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.сonditionsitem', verbose_name='Родительский пункт')),
            ],
        ),
    ]
