# Generated by Django 4.2.7 on 2024-04-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_сonditionsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='СonditionsItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название пункта')),
            ],
        ),
        migrations.CreateModel(
            name='СonditionsItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название подпункта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='goods.сonditionsitemcategory', verbose_name='Пункт')),
            ],
        ),
        migrations.DeleteModel(
            name='СonditionsItem',
        ),
    ]
