# Generated by Django 4.2.7 on 2024-04-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_сonditionsitemcategory_сonditionsitemdetail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сonditionsitemcategory',
            options={'verbose_name': 'Условия: гарантия, доставкa, оплата', 'verbose_name_plural': 'Условия: гарантия, доставкa, оплата'},
        ),
    ]
